### ISSUE TITLE
Question: Logging error details from step

### ISSUE THREAD

**Issue by vitalyal** [PragmaticFlow/NBomber#170]
Hello,
Thanks for the cool project, we decided to start our load test journey with NBomber and have a question if there are any best practices for tracking errors that happen inside step execution. 
For example if there is a bug inside test implementation or system under test is down the only way of getting error details we found so far is to attach debugger. This is kind of OK for development experience, but if something goes wrong on CI it won't be possible to understand what happened. 

We tried to investigate source code and seems that exception details are not used anywhere https://github.com/PragmaticFlow/NBomber/blob/dev/src/NBomber/Domain/Step.fs#L44

**Comment by AntyaDev** [comment]
Hi @vitalyal ,
Good question, I wanted to add them and print out them in HTML report (aggregated errors with counters) but didn't have time for it.

Quicker will be if I just start logging them, does it make sense? You then can sink your logs to ElasticSearch (it's easy to do since NBomber is using Serilog and Serilog has Elastic search sink) and analyze your log.

**Comment by vitalyal** [comment]
Hi @AntyaDev ,

Thank you, it makes sense and sounds cool!

**Comment by AntyaDev** [comment]
https://github.com/PragmaticFlow/NBomber/commit/8b79c7431a0912adc0263502bc2e35626b5743ad
https://github.com/PragmaticFlow/NBomber/releases/tag/v0.16.0
