### ISSUE TITLE
Unable to inject less than 1 request per second

### ISSUE THREAD

**Issue by neilsyrett** [PragmaticFlow/NBomber#438]
The rate parameter on the InjectPerSec() method only accepts integers. This means I am unable to inject less than 1 request per second. It would be useful to be able to use a decimal injection rate. This would bring parity with the Gatling constantUsersPerSec method.

**Comment by darraghjones** [comment]
I'd also like to be able to inject less than 1 request per second

**Comment by AntyaDev** [comment]
Hi @neilsyrett , @darraghjones 

It's on my list of things to add.
I also thought about adding something like "inject total requests"

**Comment by kweinberg1** [comment]
It's very typical for us to target a number of calls over a period of time -- usually described as "calls per hour".  

Since NBomber currently requires us to start X agents, tests will behave differently based on the number of agents, which feels like an unintended side-effect.  If we're instructing the coordinator to create some concurrency, then having a "inject total requests equally over the scenario's duration" behavior would be really beneficial.

**Comment by AntyaDev** [comment]
Hi @darraghjones @kweinberg1 @neilsyrett 
I will try to add a new simulation to cover this case

**Comment by AntyaDev** [comment]
I started working on this. 
I hope next week I will release it.

**Comment by AntyaDev** [comment]
Hi @darraghjones, @kweinberg1, @neilsyrett 
You can find it in the latest NBomber v4 beta.
