### ISSUE TITLE
Serilog Exception when trying to run a scenario

### ISSUE THREAD

**Issue by vRITHNER** [PragmaticFlow/NBomber#450]
Hi,
I'm try to run a scenario in a new net core 6.0 app console (c#) .
My goal to request an existing API call.
Some dependencies require to reference an existing Infrastructure project which use Serilog Logger.
When I run the scenario, I got each time the following error:
I try to add the appsettings + configuration builder but it doesn't change the outcome.
It would be kind if you can help me figure out what is going on.
Thanks in advance
-Vince

```
_configuration = new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json")
                    .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json", true)
                    .Build();

_loggerConfiguration = new LoggerConfiguration()
                .ReadFrom.Configuration(_configuration);
```

_loggerConfiguration.CreateLogger();

> Unhandled exception. System.MissingMethodException: Method not found: 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding, Serilog.Sinks.File.FileLifecycleHooks)'.
>    at NBomber.Infra.Logger.attachFileLogger@31(String folder, LoggerConfiguration config)
>    at NBomber.Infra.Logger.create(String folder, TestInfo testInfo, FSharpOption`1 createConfig, FSharpOption`1 configPath)
>    at NBomber.Infra.Dependency.create(String reportFolder, TestInfo testInfo, ApplicationType appType, NodeType nodeType, NBomberContext context)
>    at NBomber.DomainServices.NBomberRunner.run(NBomberContext context)
>    at NBomber.FSharp.NBomberRunner.run(NBomberContext context)
>    at NBomber.CSharp.NBomberRunner.Run(NBomberContext context)
>    at PerfTestConsole.Program.LoadTest1(Boolean skipCache, Nullable`1 siteId, Nullable`1 reportingUnitId, Nullable`1 parallelExecution)

**Comment by yurii-hunter** [comment]
Hi @vRITHNER! Could you please attach the whole project or just a test that could help to reproduce it. I will try to help you.

**Comment by szamacz** [comment]
I have experienced a similar problem, in my case I'm getting exception 
`System.MissingMethodException : Method not found: 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding, Serilog.Sinks.File.FileLifecycleHooks)'.`
This is probably because you are using Serilog.Sinks.File in version 4.1.0 and I have in my project packages with dependencies on Serilog.Sinks.File in version 5.0. When I downgraded my packages to 4.1.0 everything is fine.
Could you release a new nbomber package with Serilog.Sinks.File in version 5.0.0?

**Comment by szamacz** [comment]
Any update on this? Currently running NBomber with dotnet6 is not possible at all when you have SeriLogi.Sinks.File in version 5.0 in your project

**Comment by isaacabraham** [comment]
Linking to #458
